#!/bin/sh
dflag=
vflag=
cflag=

#Save this file into /usr/bin ensure HTS user has read/write and the file is executable

URL="http://sstv.fog.pt/epg/xmltv5.xml"
DESCRIPTION="SmoothStreamsTV"
VERSION="1.1"

if [ $# -lt 1 ]; then
    python3 /usr/bin/tvh_sstv.py
    >&2 echo "Downloading $URL..."
    wget -qO - "$URL.gz" | gzip -q -d 2>/dev/null ||
        wget -qO - "$URL" ||
            curl -s -L "$URL.gz" | gzip -q -d 2>/dev/null ||
                curl -s -L "$URL" ||
                    >&2 echo "ERROR: Failed to fetch data"
    exit 0
fi

for a in "$@"; do
  [ "$a" = "-d" -o "$a" = "--description"  ] && dflag=1
  [ "$a" = "-v" -o "$a" = "--version"      ] && vflag=1
  [ "$a" = "-c" -o "$a" = "--capabilities" ] && cflag=1
done

if [ -n "$dflag" ]; then
  echo $DESCRIPTION
fi

if [ -n "$vflag" ]; then
  echo $VERSION
fi

if [ -n "$cflag" ]; then
  echo "baseline"
fi

