#!/bin/bash
dflag=
vflag=
cflag=
if (( $# < 1 ))

#Save this into /usr/bin ensure HTS user has read/write and the file is executable


then
  python3 /usr/bin/tvh_sstv.py
  wget -q http://sstv.fog.pt/feed5.xml -O /home/hts/.xmltv/feed5.xml
  cat /home/hts/.xmltv/feed5.xml
  exit 0
fi

for arg
do
    delim=""
    case "$arg" in
    #translate --gnu-long-options to -g (short options)
       --description) args="${args}-d ";;
       --version) args="${args}-v ";;
       --capabilities) args="${args}-c ";;
       #pass through anything else
       *) [[ "${arg:0:1}" == "-" ]] || delim="\""
           args="${args}${delim}${arg}${delim} ";;
    esac
done

#Reset the positional parameters to the short options
eval set -- $args

while getopts "dvc" option 
do
    case $option in
        d)  dflag=1;;
        v)  vflag=1;;
        c)  cflag=1;;
        \?) printf "unknown option: -%s\n" $OPTARG
            printf "Usage: %s: [--description] [--version] [--capabilities] \n" $(basename $0)
            exit 2
            ;;
    esac >&2
done

if [ "$dflag" ]
then
   printf "SmoothStreamsTV\n"
fi
if [ "$vflag" ]
then
   printf "1.0\n"
fi
if [ "$cflag" ]
then
   printf "baseline\n"
fi

exit 0

